/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,html}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#f6f0e7',
        'on-primary-container': '#6b4c00',
        'surface-container-high': '#ede7df',
        'surface-variant': '#e7e2d9',
        background: '#fff9f0',
        'inverse-primary': '#ffba20',
        surface: '#fff9f0',
        'inverse-surface': '#32302a',
        'primary-fixed-dim': '#ffba20',
        'on-secondary-fixed-variant': '#93000d',
        'surface-container': '#f3ede4',
        'tertiary-fixed': '#ffdbcc',
        'surface-container-highest': '#e7e2d9',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#633d2b',
        'tertiary-container': '#efb9a1',
        'on-secondary-container': '#fffbff',
        'on-secondary-fixed': '#410002',
        'secondary-container': '#de2e2c',
        'on-tertiary-container': '#704835',
        'tertiary-fixed-dim': '#f1baa2',
        tertiary: '#7e5441',
        'on-primary-fixed-variant': '#5e4200',
        'on-surface': '#1d1b16',
        'primary-container': '#ffb800',
        'on-primary': '#ffffff',
        'surface-tint': '#7c5800',
        'on-error-container': '#93000a',
        'surface-container-low': '#f9f3ea',
        'on-tertiary-fixed': '#301305',
        secondary: '#b90c17',
        'on-error': '#ffffff',
        outline: '#837560',
        'on-background': '#1d1b16',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'outline-variant': '#d5c4ab',
        'primary-fixed': '#ffdea8',
        'on-primary-fixed': '#271900',
        'surface-dim': '#dfd9d1',
        'secondary-fixed': '#ffdad6',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#ffb4ab',
        'on-surface-variant': '#514532',
        primary: '#7c5800',
        'surface-bright': '#fff9f0',
        saffron: '#ffb800',
        paprika: '#b90c17',
        cocoa: '#301305',
        terracotta: '#993C1D',
        'terracotta-dark': '#7A2E15',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '16px',
        xs: '4px',
        lg: '40px',
        base: '8px',
        'margin-desktop': '80px',
        md: '24px',
        xl: '64px',
        sm: '12px',
      },
      fontFamily: {
        'headline-md': ['Rubik', 'sans-serif'],
        'display-md': ['Rubik', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'label-sm': ['Work Sans', 'sans-serif'],
        'headline-lg': ['Rubik', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'display-lg': ['Rubik', 'sans-serif'],
        'label-lg': ['Work Sans', 'sans-serif'],
        'headline-lg-mobile': ['Rubik', 'sans-serif'],
        accent: ['Yeseva One', 'serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-md': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
